USE WORLD;
SELECT * FROM CITY;
SELECT * FROM COUNTRY;
SELECT * FROM COUNTRYLANGUAGE;
# SELECCIONAR COLUMNAS CONCRETAS PERO TODAS LAS FILAS
SELECT NAME, CONTINENT FROM COUNTRY;
# SELECCIONAR COLUMNAS CON ALIAS, Y PONERLO EN ESPAÑOL O COMO TU QUIERAS ES CON EL AS,EL EJ ES (AS NOMBRE)
SELECT NAME AS NOMBRE, CONTINENT AS CONTINENTE FROM COUNTRY;
SELECT NAME AS PAIS, SURFACEAREA FROM COUNTRY;
 # CLAUSULA WHERE (FILTRAR LAS COLUMNAS)
 SELECT * FROM COUNTRY WHERE NAME = "SPAIN";
 # EJ 1 MUESTRA LOS PAISES DE EUROPA CON MAS DE 5M DE HABITANTES
 SELECT * FROM COUNTRY WHERE POPULATION > 5000000;
 # EJ 2 MUESTRA EL NOMBRE DE LOS PAISES CON MAS DE 80M DE HABITANTES
 SELECT * FROM COUNTRY WHERE POPULATION > 8000000;
 # EJ 3 MUESTRA LOS PAISES CUYA JEFA DE ESTADO ERA ISABEL II
 SELECT * FROM COUNTRY WHERE HEADOFSTATE = "ELISABETH II";
 
 # CLAUSULA DISTINCT (MUESTRA LOS POSIBLES VALORES DE ESA COLUMNA)
 SELECT DISTINCT CONTINENT FROM COUNTRY;

 # EJ 4 SELECCIONA LAS DISTINTAS REGIONES DE EUROPA
 SELECT DISTINCT REGION FROM COUNTRY  WHERE CONTINENT = "EUROPE";
 # EJ 5 SELECCIONA LOS DISTRITOS EN QUE SE DIVIDE ESPALA (TABLA CITY)
 SELECT DISTINCT DISTRICT FROM CITY WHERE COUNTRYCODE = "ESP";
 # FUNCION COUNT PARA SABER CUANTOS HAY SIN CONTARLOS ES 
 SELECT COUNT(*) FROM COUNTRY WHERE CONTINENT = "EUROPE";
 # EJ 6 ¿CUANTOS PAISES DE EUROPA ESTAN EN EL SUR?
 SELECT COUNT(*) FROM COUNTRY WHERE REGION = "SOUTHERN EUROPE";
 # EJ 7 ¿CUANTOS PAISES AFRICANOS TIENEN MAS DE 50M HABITANTES?
 SELECT COUNT(*) FROM COUNTRY WHERE CONTINENT = "AFRICA" AND  POPULATION > 50000000;
 # EJ 8 CUANTAS CIUDADES DE ALEMANIA HAY EN EL BBDD
 SELECT DISTINCT  DISTRICT FROM CITY WHERE COUNTRYCODE = "DEU";
 # EJ 9 QUE IDIOMAS SE HABLAN EN ESPAÑA DE FORMA OFICIAL
 SELECT * FROM COUNTRYLANGUAGE WHERE LANGUAGE = "SPANISH";
 # EJ 10 ¿EN QUE PAISES EL ESPAÑOL ES LENGUA OFICIAL?
 SELECT * FROM COUNTRYLANGUAGE WHERE COUNTRYCODE ="ESP" AND ISOFFICIAL ="T";
 # EJ 11 ¿CUANTAS CIUDADES DE ESPAÑA TIENEN MAS DE 1 M DE HABITANTES?
 SELECT COUNT(*) FROM CITY WHERE COUNTRYCODE = "ESP" AND POPULATION > 1000000;
 
 
 
 # ORDENAR UN RESULTADO ORDER BY{COLUMNA A ORDENAR} DESC/ASC DESCENDENTE O ASCENDENTE
 SELECT * FROM COUNTRY ORDER BY SURFACEAREA DESC ;
 # EJ 12 ¿CUAL ES EL PAIS MAS POBLADO DEL MUNDO?
 SELECT * FROM COUNTRY ORDER BY POPULATION DESC;
 # EJ 13 CUAL ES EL PAIS MAS POBLADO DE EUROPA
 SELECT * FROM COUNTRY WHERE CONTINENT = "EUROPE" ORDER BY POPULATION DESC;
 # EJ 14 MUESTRA LAS REGIONES DE NORTEAMERICA ORDENADAS ALFABETICAMENTE
 SELECT DISTINCT REGION FROM COUNTRY WHERE CONTINENT = "NORTH AMERICA" ORDER BY  REGION ASC;
 
# EJ 15 MUESTRA LAS 5 CIUDADES MAS POBLADAS DE ESPAÑA
SELECT * FROM CITY WHERE COUNTRYCODE = "ESP" ORDER BY POPULATION DESC LIMIT 5;
#EJ16 ¿CUALES SON LOS PAISES DEL MUNDO CON NUMERO DE HABITANTES ENTRE 1M Y 5M?
SELECT NAME FROM COUNTRY WHERE POPULATION BETWEEN 1000000 AND 5000000;
#EJ 17 ¿CUAL ES EL PAIS DE AMERICA CON MAYOR SUPERFICIE?
SELECT * FROM COUNTRY WHERE CONTINENT ="NORTH AMERICA" ORDER BY SURFACEAREA ASC;
#EJ 18 ¿CUAL ES EL PAIS DEL CARIBE CON MAYOR ESPERANZA DE VIDA?
SELECT * FROM COUNTRY WHERE REGION = "CARIBBEAN" ORDER BY LIFEEXPECTANCY DESC LIMIT 5;
# EJ 19 ¿QUE PAISES TIENEN MENOS DE 60 AÑOS DE ESPERANZA DE VIDA?
SELECT * FROM COUNTRY WHERE LIFEEXPECTANCY <60 ORDER BY LIFEEXPECTANCY DESC;
# EJ 20 MUESTRA UNA LISTA DE LAS FORMAS DE GOBIERNO ORDENADA DE FORMA ALFABETICA
SELECT DISTINCT GOVERNMENTFORM FROM COUNTRY ORDER BY GOVERNMENTFORM ASC;
#EJ 21 CUAL ES EL PAIS DE AMERICA CON MAYOR SUPERFICIE
# PUEDE HACERSE CON IN | OR | LIKE
SELECT NAME FROM COUNTRY WHERE CONTINENT LIKE "%AMERICA%" ORDER BY SURFACEAREA DESC;
# EJ 22 MUESTRA LOS PAISES QUE SON DE TIPO MONARQUIA
SELECT * FROM COUNTRY WHERE GOVERNMENTFORM = "MONARCHY";
# EJ 23 CUANTOS PAISES COMIENZAN POR LA LETRA A
SELECT COUNT(*) FROM COUNTRY WHERE NAME LIKE "A%" ORDER BY NAME ASC ;
# EJ 24 MUESTRA UNA LISTA DE LOS TIPOS DE REPUBLICAS QUE HAY, ORDENADA DE FORMA ALBAFETICA
SELECT DISTINCT GOVERNMENTFORM FROM COUNTRY WHERE GOVERNMENTFORM LIKE "%REPUBLIC%";
# EJ 25 MUESTRA LOS PAISES CON MENOS ESPERANZA DE VIDA
SELECT * FROM COUNTRY WHERE LIFEEXPECTANCY IS NOT NULL ORDER BY LIFEEXPECTANCY  LIMIT 5;

# EJ 26 CUANTOS PAISES TIENEN FECHA DE INDEPENDENCIA
SELECT COUNT(*) FROM COUNTRY WHERE INDEPYEAR IS NOT NULL;

# EJ 27 PARA CUANTOS PAISES NO DISPONEMOS DEL DATO DE ESPERANZA DE VIDA
SELECT COUNT(*) FROM COUNTRY WHERE LIFEEXPECTANCY IS NULL;
# EJ 28 CUANTAS REGIONES HAY 
SELECT DISTINCT COUNT(DISTINCT REGION) AS REGIONES FROM COUNTRY;

# OPERACIONES
SELECT "DATO" AS COLUMNA;

SELECT 2*2 AS PRODUCTO;

SELECT 2/2 AS DIVISION;

SELECT 2%2 AS "MODULO O RESTO";

SELECT "PAISES", COUNTRY.* FROM COUNTRY;

SELECT NAME, POPULATION*0 FROM COUNTRY;
# EJ 29 MUESTRA UNA LISTA DE PAISES Y SU DENSIDAD DE POBLACION
SELECT NAME, POPULATION/SURFACEAREA AS DENSIDAD FROM COUNTRY;
# EJ 30 MUESTRA EL PRODUCTO NACIONAL BRUTO (GNP) PER CAPITA ARGENTINA
SELECT NAME, GNP*1000000/POPULATION AS GNP_PER_CAPITA FROM COUNTRY WHERE NAME = "ARGENTINA";
# EJ 31 MUESTRA LOS 5 PAISES MAS GRANDES (POR SUPERFICIE) DE EUROPA
SELECT NAME, POPULATION/SURFACEAREA AS DENSIDAD FROM COUNTRY ORDER BY DENSIDAD DESC;
# EJ 32 MUESTRA LOS 5 PAISES MAS DENSAMENTE POBLADOS DE EUROPA
SELECT NAME, POPULATION/SURFACEAREA AS DENSIDAD FROM COUNTRY  WHERE CONTINENT = "EUROPE" ORDER BY DENSIDAD DESC LIMIT 5;
# EJ 33 MUESTRA LOS 5 PAISES MENOS DENSAMENTE POBLADOS EUROPA
SELECT NAME, POPULATION/SURFACEAREA AS DENSIDAD FROM COUNTRY WHERE CONTINENT = "EUROPE" ORDER BY DENSIDAD ASC LIMIT 5;

# OPERACIONES DE AGREGACION 
# - COUNT CUENTA FILAS
# - SUM SUMA EL VALOR DE LAS FILAS
# - AVG CALCULA EL VALOR  MEDIO DE LOS DATOS DE LA COLUMNA INDICADA
# - MIN MUESTRA EL VALOR MINIMO DE LA COLUMNA INDICADA
# - MAX MUESTRA EL VALOR MAXIMO DE LA COLUMNA INDICADA 
# EJ 34 CUAL ES LA POBLACION MUNDIAL
SELECT SUM(POPULATION) FROM COUNTRY;

# EJ 35 CUAL ES LA ESPERANZA DE VIDA MEDIA DE AFRICA
SELECT AVG(LIFEEXPECTANCY) FROM COUNTRY WHERE CONTINENT = "AFRICA";
# EJ 36 ¿CUAL ES LA SUPERFICIE TOTAL DEL MUNDO?
SELECT SUM(SURFACEAREA) FROM COUNTRY;
# EJ 37 ¿CUANTAS CIUDADES DE ANDALUCIA HAY EN LA BBDD?
SELECT COUNT(*) FROM CITY WHERE DISTRICT = "ANDALUSIA";
# EJ 38 ¿CUAL ES EL VALOR MAXIMO DEL GNP?,¿A QUE PAIS CORRESPONDE?
SELECT NAME, GNP FROM COUNTRY WHERE GNP = (SELECT MAX(GNP)FROM COUNTRY);
# EJ 39 ¿CUAL ES EL VALOR MINIMO DEL GNP?¿A QUE PAIS CORRESPONDE?
SELECT NAME, GNP FROM COUNTRY WHERE GNP = (SELECT MIN(GNP)FROM COUNTRY);
# EJ 40 ¿EN QUE AÑO, DE MEDIA, SE INDEPENDIZARON LOS PAISES DE SUDAMERICA?
SELECT AVG(INDEPYEAR) FROM COUNTRY WHERE CONTINENT = "SOUTH AMERICA";
# EJ 41 ¿CUAL ES EL PAIS CON FECHA DE INDEPENDENCIA MAS CERCANA A HOY?
SELECT NAME, INDEPYEAR FROM COUNTRY WHERE INDEPYEAR = (SELECT MAX(INDEPYEAR)FROM COUNTRY);
#EJ 42 ¿QUE PAISES AMERICANOS  TIENEN MAS POBLACION QUE ESPAÑA?
SELECT NAME FROM COUNTRY WHERE CONTINENT LIKE "%AMERICA%" AND POPULATION > (SELECT POPULATION FROM COUNTRY WHERE NAME = "SPAIN");
#EJ 43 ¿CUAL ES LA CIUDAD CON EL MAYOR POBLACION?
SELECT NAME, POPULATION FROM CITY WHERE POPULATION = (SELECT MAX(POPULATION) FROM CITY);
# EJ 44 ¿QUE PAISES TIENEN MENOS POBLACION QUE MADRID?
SELECT NAME, POPULATION FROM COUNTRY WHERE POPULATION < (SELECT POPULATION FROM CITY WHERE NAME = "MADRID"); 
# EJ 45 ¿HAY ALGUNA CIUDAD QUE SE LLAME IGUAL QUE EL PAIS?
SELECT NAME FROM CITY WHERE NAME IN (SELECT NAME FROM COUNTRY); 
# EJ 46 ¿QUE PAISES DE EUROPA Y ASIA TIENE UNA POBLACION POR ENCIMA DE LA MEDIA DE ESOS CONTINENTES?
SELECT AVG(POPULATION) FROM COUNTRY WHERE CONTINENT IN ("EUROPE", "ASIA") AND POPULATION > (SELECT AVG(POPULATION)FROM COUNTRY WHERE CONTINENT IN ("EUROPE", "ASIA"));
# EJ 47 ¿HAY ALGUN PAIS SIN CIUDADES EN LA BBDD?
SELECT * FROM COUNTRY WHERE CODE NOT IN(SELECT COUNTRYCODE FROM CITY);
# EJ 48 ¿CUANTAS CIUDADES NO SON CAPITALES?
SELECT NAME FROM CITY WHERE ID NOT IN (SELECT CAPITAL FROM COUNTRY WHERE CAPITAL IS NOT NULL);

# EJ 49 ¿CUAL ES LA POBLACION MEDIA DE LAS  CIUDADES EUROPEAS?
SELECT AVG(POPULATION) AS POBLACION_MEDIA FROM CITY WHERE COUNTRYCODE IN (SELECT CODE FROM COUNTRY WHERE CONTINENT="EUROPE");
# EJ 50 ¿CUAL ES LA POBLACION MEDIA DE LAS CAPITALES AMERICANAS?
SELECT AVG(CAPITAL) FROM COUNTRY WHERE CONTINENT LIKE "%AMERICA%";

# EJ 51 MUESTRA EL NOMBRE, LA SUPERFICIE, LA POBLACION Y LA DENSIDAD DE POBLACION DE JAPON Y ESPAÑA
SELECT NAME, SURFACEAREA, POPULATION,POPULATION/SURFACEAREA AS DENSIDAD_POBLACION FROM COUNTRY WHERE NAME="SPAIN" OR NAME="JAPAN";
#EJ 52 MUESTRA EL NOMBRE DE LOS PAISES QUE HABLAN FRANCES DE FORMA OFICIAL
SELECT NAME FROM COUNTRY WHERE CODE IN (SELECT COUNTRYCODE FROM COUNTRYLANGUAGE WHERE LANGUAGE = "FRENCH" AND ISOFFICIAL = "T");
#EJ 53 MUESTRA LA POBLACION TOTAL DE LOS PAISES QUE HABLAN ESPAÑOL DE FORMA OFICIAL
SELECT SUM(POPULATION) AS POBLACION_HISPANOS FROM COUNTRY WHERE CODE IN (SELECT COUNTRYCODE FROM COUNTRYLANGUAGE WHERE LANGUAGE = "SPANISH" AND ISOFFICIAL = "T");
#EJ 54 EN QUE REGIONES SE HABLA ESPAÑOL (OFICIAL Y NO OFICIAL)
SELECT DISTINCT REGION FROM COUNTRY WHERE CODE IN (SELECT COUNTRYCODE FROM COUNTRYLANGUAGE WHERE LANGUAGE = "SPANISH");
#EJ ------
SELECT CONTINENT, SUM(POPULATION) FROM COUNTRY GROUP BY CONTINENT ORDER BY CONTINENT; #HACE GRUPOS
#EJ 55 MUESTRA LA ESPERANZA DE VIDA MEDIA POR CONTINENTE
SELECT CONTINENT, AVG(LIFEEXPECTANCY) FROM COUNTRY GROUP BY CONTINENT;
#EJ 56 MUESTRA LAS REGIONES Y LA SUPERFICIE TOTAL DE CADA REGION
SELECT REGION, SUM(SURFACEAREA) FROM COUNTRY GROUP BY REGION;
#EJ 57 MUESTRA EL AÑO DE INDEPENDENCIA PROMEDIO DE CADA CONTIENENTE (SIN TENER EN CUENTA LOS NULOS)
SELECT CONTINENT, AVG(INDEPYEAR) FROM COUNTRY GROUP BY CONTINENT;
#EJ 58 MUESTRA LOS DISTRITOS DE ESPAÑA (TABLA CITY) Y LA POBLACION TOTAL DE CADA UNO
SELECT DISTRICT, SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = "ESP" GROUP BY DISTRICT;
#EJ 59 SUMA EL PORCENTAJE TOTAL DE TODOS LOS IDIOMAS AGRUPANDO POR PAIS
SELECT COUNTRYCODE, SUM(PERCENTAGE) FROM COUNTRYLANGUAGE ORDER BY COUNTRYCODE;
SELECT* FROM COUNTRYLANGUAGE;
#EJ 60 MUETSRA EL NOMBRE DE LAS REGIONES CON MAS DE 10M DE HABITANTES
SELECT REGION FROM COUNTRY GROUP BY REGION HAVING SUM(POPULATION)>10000000;
#EJ 61 MUESTRA EL NOMBRE DE LAS REGIONES DE ASIA Y AMERICA CON MAS DE 100M DE HABITANTES
SELECT REGION FROM COUNTRY WHERE REGION = "ASIA" OR CONTINENT LIKE  "%AMERICA%" GROUP BY REGION HAVING SUM(POPULATION)>100000;
#EJ 62 MUESTRA LOS DISTRITOS DE EUROPA CON MAS DE 3M DE HABITANTES
SELECT * FROM CITY WHERE COUNTRYCODE IN (SELECT CODE FROM COUNTRY WHERE CONTINENT = "EUROPE");
SELECT * FROM COUNTRY;
#EJ 63 MUESTRA UNA LISTA DE LOS CONTINENTES Y CUANTOS PAISES HAY EN CADA CONTINENTE
SELECT DISTRICT, SUM(POPULTION) AS POBLACION_DISTRITO FROM CITY WHERE COUNTRYCODE IN (SELECT CODE FROM COUNTRY WHERE CONTINENT = "EUROPE" GROUP BY DISTRICT HAVING POBLACION_DISTRITO>3000000);
#EJ 64 MUESTRA UNA LISTA DE LAS REGIONES Y CUANTOS PAISES HAY EN CADA REGION
SELECT REGION, COUNT(NAME) FROM COUNTRY GROUP BY REGION;
SELECT * FROM COUNTRY;
#EJ 65 MUESTRA EL NOMBRE DE LOS PAISES CON MAS DE 1 IDIOMA OFICIAL
SELECT NAME FROM COUNTRY WHERE CODE IN (SELECT COUNTRYCODE  AS IDIOMAS_OFICIALES FROM COUNTRYLANGUAGE WHERE ISOFFICIAL ="T" GROUP BY COUNTRYCODE HAVING COUNT(*)>1);
SELECT * FROM COUNTRYLANGUAGE;
#EJ 66 MUESTRA EL NOMBRE DE LOS PAISES EUROPEOS CON MAS DE 1 IDIOMA OFICIAL 
#SELECT NAME FROM COUNTRY WHERE CONTINENT = "EUROPE" AND CODE IN (SELECT COUNTRYCODE; #COUNT(*) AS IDIOMAS_OFICIALES FROM COUNTRYLANGUAGE WHERE ISOFFICIAL ="T" GROUP BY COUNTRYCODE HAVING COUNT(*)>1);


#=============================FUNCIONES====================================#
# CONCAT()

SELECT NAME, CONCAT(CONTINENT,"-", REGION) AS CONTINENTE FROM COUNTRY;
#LOWER() -> PONE EN MINUSCULA
#UPPER() -> PONE EN MAYUSCULA

SELECT UPPER(NAME) FROM COUNTRY;
SELECT LOWER(NAME) FROM COUNTRY;

# LEFT(cadena, n)->   n PRIMEROS CARACTERES
# RIGHT (cadena, n)-> n ULTIMOS CARACTERES
# MID (cadena, p, n) -> O SUBSTR() -> n CARACTERES DESDE LA POSICION p
SELECT LEFT("CADENA DE TEXTO", 5);
SELECT RIGHT("CADENA DE TEXTO", 5);
SELECT MID("CADENA DE TEXTO", 8,2);

SELECT UPPER(LEFT(NAME,3)) FROM COUNTRY;

# EJ 67 SELECCIONA EL CODIGO DE LOS PAISES, LAS 3 PRIMERAS LETRAS DE SU NOMBRE EN MAYUSCULA Y UNA COLUMNA QUE INDIQUE SI LAS DOS ANTERIORES COINCIDEN
SELECT CODE,UPPER(LEFT(NAME,3)) AS INICIALES, CODE=(LEFT(NAME,3)) AS COINCIDEN FROM COUNTRY;
# EJ 68 ¿PARA CUANTOS PAISES COINCIDE EL CODIGO CON LAS 3 PRIMERAS LETRAS DE SU NOMBRE?
SELECT SUM(CODE=UPPER(LEFT(NAME,3))) AS COINCIDEN FROM COUNTRY;
# ES LA MAS SIMPLE LA DE ABAJO 
SELECT COUNT(*) FROM COUNTRY WHERE CODE=LEFT(NAME,3);


# REPEAT (cadena, n) -> REPITE UNA CADENAn VECES
SELECT REPEAT("*", 8); 	


SELECT REPEAT(NAME,2) FROM COUNTRY;

#REPLACE (cadena, subcadena_anterior, subcadena_nueva) 
# REEMPLAZA LA SUBCADENA BUSCADA POR UNA NUEVA
SELECT REPLACE("ESTO ES UNA CADENA DE TEXTO", "CADENA", "OTRA COSA");

SELECT REPLACE(HEADOFSTATE, "Elisabeth", "Isabel") FROM COUNTRY;
# REVERSE() -> INVIERTE UNA CADENA DE TEXTO
SELECT REVERSE("123456789");
SELECT REVERSE(GOVERNMENTFORM) FROM COUNTRY;
#=====================================FUNCIONES NUMERICAS ==================================================#
# SQRT -> RAIZ CUADRADA
SELECT SQRT(9);
#EJ 69 ¿SI ESPAÑA FUESE UN CUADRADO, CUANTOS KILOMENTROS DE LADO TENDRIA?
SELECT SQRT(SURFACEAREA) AS LADO_ESPAÑITA FROM COUNTRY WHERE NAME = "SPAIN";
# ROUND -> REDONDEA(NUMERO, DECIMALES)
SELECT ROUND(1.69);
# TRUNCATE(NUMERO,DECIMALES) TRUNCA SIN DECIMALES 
SELECT TRUNCATE(7.896532,3);
# FLOOR(NUMERO) -> ENTERO INFERIOR
SELECT FLOOR(7.896523);
# CEIL(NUMERO) -> ENTERO SUPERIOR
SELECT CEIL(7.1);
# POWER LO QUE HACE ES ELEVAR -> 2^10
SELECT POWER(2,10); # LO QUE HACE ES ELEVAR -> 2^10
# RAND () -> NUMERO ALEATORIO ENTRE 0 Y 1
#EJ 70 GENERA UN NUMERO ALEATORIO ENTRE 1 Y 10
SELECT RAND()*10+1;
SELECT CEIL(RAND()*10);
SELECT * FROM COUNTRY;
#======================================JOIN===========================================#
SELECT * FROM COUNTRY;

SELECT * FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE;

#EJ 71 MUESTRA UNA LISTA DE LAS CIUDADES DE ESPAÑA, SU POBLACION, LA POBLACION DEL PAIS Y EL % DE
# POBLACION DEL PAIS QUE VIVE EN ESA CIUDAD (2 DECIMALES)
SELECT 
	CITY.NAME,
	CITY.POPULATION, 
	COUNTRY.POPULATION,
    ROUND(CITY.POPULATION/COUNTRY.POPULATION*100, 2) AS POBLACION_EN_CIUDAD
    FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.NAME="SPAIN";
# EJ 72 MUESTRA UNA LISTA DE LOS DISTRITOS DE ESPAÑA, SU POBLACION, 
#LA POBLACION DEL PAIS Y EL PORCENTAJE DE POBLACION DEL PAIS QUE VIVE EN ESE DISTRITO (2 DECIMALES)
SELECT * FROM CITY;
SELECT 
	DISTRICT,
    SUM(CITY.POPULATION) AS POBLACION_DISTRITO, 
    MAX(COUNTRY.POPULATION) AS PORCENTAJE_DISTRITO,
	ROUND(SUM(CITY.POPULATION)/MAX(COUNTRY.POPULATION)*100, 2)  AS DECIMALES
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE COUNTRY.NAME="SPAIN" 
GROUP BY DISTRICT;
#EJ 73 MUESTRA UNA LISTA DE LAS CAPITALES EUROPEAS USANDO JOIN
SELECT CITY.NAME FROM COUNTRY 
JOIN CITY ON COUNTRY.CAPITAL = CITY.ID WHERE COUNTRY.CONTINENT = "EUROPE";
SELECT * FROM CITY;
#EJ 74 ¿CUAL ES LA CAPITAL DEL MUNDO MAS POBLADA?
SELECT CITY.NAME FROM COUNTRY JOIN CITY ON COUNTRY.CAPITAL = CITY.ID ORDER BY CITY.POPULATION DESC LIMIT 1; 
#EJ 75 MUESTRA UNA LISTA CON EL NOMBRE DE LOS PAISES
SELECT  CO.NAME,
		COUNT(CL.LANGUAGE) AS IDIOMAS
FROM COUNTRY AS CO
JOIN COUNTRYLANGUAGE AS CL ON CO.CODE= CL.COUNTRYCODE
GROUP BY CO.NAME;
#EJ 76 MUESTRA UNA LISTA CON EL NOMBRE LOS PAISES Y LA CANTIDAD DE IDIOMAS QUE SE HABLA EN DICHO PAIS
SELECT  CO.NAME,
		COUNT(CL.LANGUAGE) AS IDIOMAS
FROM COUNTRY AS CO
JOIN COUNTRYLANGUAGE AS CL ON CO.CODE= CL.COUNTRYCODE
WHERE CL.ISOFFICIAL = "T"
GROUP BY CO.NAME;
#EJ 77 MUESTRA UNA LISTA CON EL NOMBRE DE TODOS PAISES Y LA CANTIDAD DE CIUDADES DE CADA PAIS DISPONIBLES EN LA BASE DE DATOS
SELECT * FROM COUNTRY;
SELECT * FROM CITY;
SELECT COUNTRY.NAME, COUNT(CITY.NAME) AS CANTIDAD FROM CITY JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE GROUP BY COUNTRY.NAME;
#EJ 78 MUESTRA EL NOMBRE DE LOS PAISES SIN CIUDADES REGISTRADAS
SELECT NAME FROM COUNTRY WHERE CODE NOT IN (SELECT COUNTRYCODE FROM CITY); #1º FORMA SUBCONSULTA

SELECT * FROM COUNTRY AS CO LEFT JOIN CITY AS CI ON CI.COUNTRYCODE=CO.CODE WHERE CI.NAME IS NULL; #2º FORMA JOIN
#EJ 79 MUESTRA UNA LISTA CON EL NOMBRE DE LOS PAISES, LOS IDIOMAS HABLADOS Y LA CANTIDAD DE PERSONAS
#QUE HABLAN CADA IDIOMA EN CADA PAIS
SELECT COUNTRY.NAME, COUNTRYLANGUAGE.LANGUAGE AS LENGUAJE, ((COUNTRY.POPULATION/100)*COUNTRYLANGUAGE.PERCENTAGE) AS CANTIDAD FROM COUNTRY JOIN COUNTRYLANGUAGE ON COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE;
#EJ 80 MUESTRA UNA LISTA CON EL NOMBRE DE LA CAPITAL DE LOS PAISES CON ESPAÑOL COMO IDIOMA OFICIAL
SELECT CI.NAME FROM CITY AS CI JOIN COUNTRY AS CO ON CI.COUNTRYCODE = CO.CODE WHERE CI.COUNTRYCODE IN(SELECT CO.CAPITAL AND CL.ISOFFICIL="T");
# EJ82 - MUESTRA UNA LISTA CON LOS IDIOMAS Y EL PORCENTAJE DE LA POBLACIÓN MUNDIAL QUE HABLA CADA IDIOMA (ORDENA DE MAYOR A MENOR).
SELECT COUNTRYLANGUAGE.LANGUAGE ((SUM(COUNTRYPOPULATION)*COUNTRYLANGUAGE/100))*SUM(COUNTRYLANGUAGE.PERCENTAGE) 
AS IDIOMA 
FROM COUNTRY
JOIN COUNTRYLANGUAGE ON COUNTRY.CODE=COUNTRYLANGUAGE.COUNTRYCODE GROUP BY COUNTRYLANGUAGE.LANGUAGE ORDER BY IDIOMA DESC;
# EJ83 - MUESTRA TODAS LAS CIUDADES QUE NO SON CAPITALES.

