DROP SCHEMA IF EXISTS ACTUACIONES;
CREATE SCHEMA ACTUACIONES;
USE ACTUACIONES;

# (ID, PAIS, CIUDAD, DIRECCION, TLFN, DIRECTOR)
CREATE TABLE SEDE(
ID INT PRIMARY KEY AUTO_INCREMENT,
PAIS VARCHAR (30), 
CIUDAD VARCHAR (30), 
DIRECCION VARCHAR(100),
TELEFONO VARCHAR (15) UNIQUE,
DIRECTOR VARCHAR (50)
);
#PROYECTO: (COD, TITULO, F.INICIO, F.FIN, PRESUPUESTO, RESPONSABLE, ID_SEDE)

CREATE TABLE PROYECTO(
CODIGO INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR (50),
FECHA_INICIO DATE, 
FECHA_FIN DATE,
PRESUPUESTO DECIMAL (9,2), 
RESPONSABLE VARCHAR (50),
ID_SEDE INT,

FOREIGN KEY (ID_SEDE) REFERENCES ID(SEDE),
CONSTRAINT FECHA_FIN_POSTERIOR CHECK (FECHA_FIN>FECHA_INICIO)
);

CREATE TABLE POBLACION(
NOMBRE CHAR(30), 
PAIS VARCHAR(50),
ID INT PRIMARY KEY AUTO_INCREMENT, 
NUMERO_HABITANTES INT

);
#ACTUACION: (COD, ESC, INVERSION, ID_POBLACION, CODIGO_PROYECTO)
CREATE TABLE ACTUACION (
CODIGO INT PRIMARY KEY,
DESCRIPCION VARCHAR (30),
INVERSION DECIMAL (9,2), 
CODIGO_PROYECTO INT,
ID_POBLACION INT,
FOREIGN KEY (ID_POBLACION) REFERENCES POBLACION(ID),
FOREIGN KEY (CODIGO_PROYECTO) REFERENCES PROYECTO(CODIGO)
);
# RESTRICCIONES #
#UNIQUE --> SIN REPETIDOS 
#NOT NULL --> ME OBLIGA A QUE TENGA ALGÚN DATO 
#DEFAULT --> PONER EL VALOR POR DEFECTO 
