DROP SCHEMA IF EXISTS AEROLINEAS;
CREATE SCHEMA AEROLINEAS;
USE AEROLINEAS;
CREATE TABLE PROGRAMA_VUELO(
COMPAÑIA VARCHAR (50),
RUTA VARCHAR (50),
CODIGO_DESPEGUE INT,
CODIGO_ATERRIZAJE INT,
PRIMARY KEY (COMPAÑIA, RUTA),
FOREIGN KEY (CODIGO_DESPEGUE) REFERENCES DESPEGUE(CODIGO),
FOREIGN KEY (CODIGO_ATERRIZAJE) REFERENCES ATERRIZAJE(CODIGO)
);
INSERT INTO PROGRAMA_VUELO VALUES

SELECT * FROM PROGRAMA_VUELO;

CREATE TABLE DIAS(
LETRA VARCHAR (50),
NOMBRE VARCHAR (50),
PRIMARY KEY (LETRA,NOMBRE)
);
INSERT INTO PROGRAMA_VUELO VALUES

SELECT * FROM PROGRAMA_VUELO;

CREATE TABLE PROGRAMA_VUELO_DIAS(
COMPAÑIA_PROGRAMA_VUELO VARCHAR (50),
RUTA_PROGRAMA_VUELO VARCHAR (50),
DIA VARCHAR (9),
LETRA_DIAS VARCHAR(50),
NOMBRE_DIAS VARCHAR(50),
PRIMARY KEY (COMPAÑIA_PROGRAMA_VUELO,RUTA_PROGRAMA_VUELO,LETRA_DIAS,NOMBRE_DIAS),
FOREIGN KEY (COMPAÑIA_PROGRAMA_VUELO, RUTA_PROGRAMA_VUELO) REFERENCES PROGRAMA_VUELO(COMPAÑIA,RUTA),
FOREIGN KEY (LETRA_DIAS, NOMBRE_DIAS) REFERENCES DIAS(LETRA,NOMBRE),
CONSTRAINT DIA_OK CHECK (DIA IN ("LUNES","MARTES","MIERCOLES","JUEVES","VIERNES","SABADO","DOMINGO"))
);
INSERT INTO PROGRAMA_VUELO VALUES

SELECT * FROM PROGRAMA_VUELO;

CREATE TABLE AEROPUERTO(
CODIGO INT PRIMARY KEY,
NOMBRE VARCHAR (50) UNIQUE NOT NULL,
CIUDAD VARCHAR (50),
PAIS VARCHAR(50)
);
INSERT INTO PROGRAMA_VUELO VALUES

SELECT * FROM PROGRAMA_VUELO;

CREATE TABLE MODELO_AVION(
NOMBRE VARCHAR (50) PRIMARY KEY,
CAPACIDAD SMALLINT NOT NULL,
CONSTRAINT CAPACIDAD_2_200 CHECK (CAPACIDAD BETWEEN 2 AND 200)
);
INSERT INTO PROGRAMA_VUELO VALUES

SELECT * FROM PROGRAMA_VUELO;

CREATE TABLE VUELO(
NUMERO_VUELO INT PRIMARY KEY,
FECHA DATE NOT NULL,
PLAZAS_VACIAS SMALLINT DEFAULT 10 NOT NULL,
COMPAÑIA_PROGRAMA_VUELO VARCHAR (50) NOT NULL,
RUTA_PROGRAMA_VUELO VARCHAR (50) NOT NULL,
NOMBRE_MODELO_AVION VARCHAR (50),
FOREIGN KEY (COMPAÑIA_PROGRAMA_VUELO,RUTA_PROGRAMA_VUELO) REFERENCES PROGRAMA_VUELO(COMPAÑIA, RUTA),
FOREIGN KEY (NOMBRE_MODELO_AVION) REFERENCES MODELO_AVION(NOMBRE),
CONSTRAINT FECHA_MAS_1930 CHECK (FECHA > "1930-01-01")
);
INSERT INTO PROGRAMA_VUELO VALUES

SELECT * FROM PROGRAMA_VUELO;

CREATE TABLE MODELO_AVION_PUEDE_ATERRIZAR_EN_AEROPUERTO(
NOMBRE_MODELO VARCHAR (50) NOT NULL,
CODIGO_AEROPUERTO VARCHAR (50) NOT NULL,
PRIMARY KEY (NOMBRE_MODELO, CODIGO_AEROPUERTO),
FOREIGN KEY (NOMBRE_MODELO) REFERENCES MODELO(NOMBRE),
FOREIGN KEY (CODIGO_AEROPUERTO) REFERENCES AEROPUERTO(CODIGO)
);
INSERT INTO PROGRAMA_VUELO VALUES

SELECT * FROM PROGRAMA_VUELO;