DROP SCHEMA IF EXISTS ANUNCIOS;
CREATE SCHEMA ANUNCIOS;
USE ANUNCIOS;
CREATE TABLE CLIENTE(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (50),
DIRECCION VARCHAR (50),
TELEFONO VARCHAR (15) UNIQUE,
E_MAIL VARCHAR (50) UNIQUE
);
INSERT INTO CLIENTE VALUES
("123456789","Jose Ramirez","C/Cajuelas","672548965","jose83@gmail.com");
SELECT * FROM CLIENTE;
CREATE TABLE ANUNCIO(
CODIGO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (30) NOT NULL,
TIPO VARCHAR(50),
TITULO VARCHAR(30),
CONTENIDO MEDIUMTEXT, #DEFAULT "CONTENIDO MARCA ACME",
CATEGORIA VARCHAR (50), 
PRECIO DECIMAL (9,2),
ID_CLIENTE INT,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
CONSTRAINT PRECIO_POSITIVO CHECK (PRECIO>0)
);
INSERT INTO ANUNCIO VALUES 
("456357159","JOSE RAMIREZ","CORTO","EL PESAR DE AGATHA","SUSPENSE","MIEDO","200", "123456789");
SELECT * FROM ANUNCIO;
CREATE TABLE WEB(
URL VARCHAR(255) PRIMARY KEY, 
NOMBRE VARCHAR (50),
TOPICO VARCHAR (50)
);
CREATE TABLE ANUNCIO_PERTENECE_WEB(
CODIGO_ANUNCIO INT,
URL_WEB VARCHAR (255),
FECHA_INICIO DATETIME,
FECHA_FIN DATETIME,
PRIMARY KEY (CODIGO_ANUNCIO, URL_WEB, FECHA_INICIO),
FOREIGN KEY (CODIGO_ANUNCIO) REFERENCES ANUNCIO(CODIGO),
FOREIGN KEY (URL_WEB) REFERENCES WEB(URL),
CONSTRAINT TIEMPO_OK CHECK (FECHA_FIN>FECHA_INICIO)
);