DROP SCHEMA IF EXISTS CARRERAS;
CREATE SCHEMA CARRERAS;
USE CARRERAS;
CREATE TABLE PARTICIPANTE(
DNI CHAR (9) PRIMARY KEY,
NOMBRE VARCHAR (30)
); 
CREATE TABLE ORGANIZADOR(
DNI CHAR (9) PRIMARY KEY,
NOMBRE VARCHAR (30),
EDAD TINYINT,
CARGO VARCHAR (50),
FECHA_INICIO DATETIME
);
CREATE TABLE ORGANIZADOR_DIRECTOR(
DNI_DIRECTOR CHAR (9) PRIMARY KEY,
CURRICULUM MEDIUMBLOB,
FOREIGN KEY (DNI_DIRECTOR) REFERENCES ORGANIZADOR(DNI)
);
CREATE TABLE CARRERA(
ID INT PRIMARY KEY AUTO_INCREMENT,
FECHA DATETIME,
LUGAR_INICIO VARCHAR (50),
LUGAR_FIN VARCHAR (50), 
DNI_DIRECTOR CHAR (9),
FOREIGN KEY (DNI_DIRECTOR) REFERENCES ORGANIZADOR_DIRECTOR(DNI_DIRECTOR)
);
CREATE TABLE ETAPA(
 ID INT PRIMARY KEY AUTO_INCREMENT,
 NUMERO_ETAPA INT,
 KM_TOTALES SMALLINT, 
 ID_CARRERA INT,
 FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
 );
CREATE TABLE CARRERA_A_PIE(
ID_CARRERA INT PRIMARY KEY AUTO_INCREMENT,
DESNIVEL FLOAT,
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);
CREATE TABLE CARRERA_CICLISTA(
ID_CARRERA INT PRIMARY KEY AUTO_INCREMENT,
TEMPERATURA FLOAT,
LLUEVE BOOLEAN,
FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE BICICLETA(
ID INT PRIMARY KEY AUTO_INCREMENT, 
MODELO VARCHAR (50), 
ES_ELECTRICA VARCHAR (30),
PESO SMALLINT
);
CREATE TABLE PARTICIPANTE_PARTICIPA_CARRERA(
DNI_PARTICIPANTE CHAR (9),
 ID_CARRERA INT, 
 NUMERO_DORSAL INT,
 PRIMARY KEY(DNI_PARTICIPANTE,ID_CARRERA),
 FOREIGN KEY(DNI_PARTICIPANTE) REFERENCES PARTICIPANTE(DNI),
 FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);
CREATE TABLE ORGANIZADOR_ASISTE_CARRERA(
DNI_ORGANIZADOR CHAR (9),
ID_CARRERA INT,
PRIMARY KEY(DNI_ORGANIZADOR, ID_CARRERA),
FOREIGN KEY(DNI_ORGANIZADOR) REFERENCES ORGANIZADOR(DNI),
FOREIGN KEY(ID_CARRERA) REFERENCES CARRERA(ID)
);
CREATE TABLE CARRERA_CICLISTA_PERMITE_BICICLETA(
ID_CARRERA_CICLISTA INT, 
ID_BICICLETA INT,
PRIMARY KEY()
);