DROP SCHEMA IF EXISTS SEGUROS;
CREATE SCHEMA SEGUROS;
USE SEGUROS;
# USANDO EXPRESIONES REGULARES, VALIDA EL DNI Y LA MATRICULA DEL VEHICULO
# LAS CUANTIAS DEBEN SER POSITIVAS
CREATE TABLE CLIENTE(
DNI CHAR (9) PRIMARY KEY,
NOMBRE VARCHAR (30),
FECHA_NACIMIENTO DATETIME,
FECHA_PERMISO DATETIME
CONSTRAINT DNI_VALIDO CHECK (DNI RLIKE "[0-9]{8}[A-Z]")
);
CREATE TABLE VEHICULO(
MATRICULA INT,
NUMERO_BASTIDOR INT PRIMARY KEY,
MARCA VARCHAR (50),
MODELO VARCHAR(50),
COLOR VARCHAR (30),
FECHA_PRIMERA_MATRICULA DATETIME
);
CREATE TABLE POLIZA(
NUMERO_POLIZA INT PRIMARY KEY, 
PRECIO DECIMAL (9,2),
DNI_CLIENTE CHAR (9),
NUMERO_BASTIDOR_VEHICULO INT,
FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI),
FOREIGN KEY (NUMERO_BASTIDOR_VEHICULO) REFERENCES VEHICULO(NUMERO_BASTIDOR)
);
CREATE TABLE COBERTURA(
CODIGO INT PRIMARY KEY,
 TIPO VARCHAR (50),
 CUANTIA DECIMAL (9,2)
);
CREATE TABLE SINIESTRO(
ID INT PRIMARY KEY AUTO_INCREMENT,
FECHA DATE,
LUGAR VARCHAR(50), 
CAUSA VARCHAR(50), 
CUANTIA DECIMAL (9,2),
NUMERO_POLIZA_POLIZA INT,
FOREIGN KEY (NUMERO_POLIZA_POLIZA) REFERENCES POLIZA(NUMERO_POLIZA)
);
CREATE TABLE CLIENTE_ASEGURA_VEHICULO(
DNI_CLIENTE CHAR(9),
NUMERO_BASTIDOR_VEHICULO INT,
 PRIMARY KEY(DNI_CLIENTE, NUMERO_BASTIDOR_VEHICULO),
 FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI),
 FOREIGN KEY(NUMERO_BASTIDOR_VEHICULO) REFERENCES VEHICULO(NUMERO_BASTIDOR)
);
CREATE TABLE POLIZA_ASEGURA_COBERTURA(
NUMERO_POLIZA_POLIZA INT,
CODIGO_COBERTURA INT,
PRIMARY KEY(NUMERO_POLIZA_POLIZA, CODIGO_COBERTURA),
FOREIGN KEY (NUMERO_POLIZA_POLIZA) REFERENCES POLIZA(NUMERO_POLIZA),
FOREIGN KEY (CODIGO_COBERTURA) REFERENCES COBERTURA(CODIGO)
);
#--------------------------------Restricciones----------------#



