DROP SCHEMA IF EXISTS CLIENTES;
CREATE SCHEMA CLIENTES;
USE CLIENTES;
CREATE TABLE CLIENTE(
ID INT PRIMARY KEY AUTO_INCREMENT,
SALDO DECIMAL (9,2) DEFAULT 0,
DESCUENTO DECIMAL (3,2),
CONSTRAINT DESCUENTO_0_1 CHECK (DESCUENTO BETWEEN 0 AND 1)
);

INSERT INTO CLIENTE VALUES
(DEFAULT,"1000",DEFAULT);
SELECT * FROM CLIENTE;

CREATE TABLE DIRECCIONES(
ID INT PRIMARY KEY AUTO_INCREMENT,
NUMERO TINYINT,
CALLE VARCHAR (50),
PUEBLO VARCHAR (50),
CIUDAD VARCHAR (50)
);

INSERT INTO DIRECCIONES VALUES
(DEFAULT, "21","CALLE MIRA","MORALEJA DE ENMEDIO","MADRID");
SELECT * FROM DIRECCIONES;

CREATE TABLE PEDIDO(
ID INT PRIMARY KEY AUTO_INCREMENT,
FECHA_HORA DATETIME,
ID_CLIENTE INT,
ID_DIRECCIONES INT,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (ID_DIRECCIONES) REFERENCES DIRECCIONES(ID)
);
INSERT INTO PEDIDO VALUES
(DEFAULT, "2023-02-02 23:40",DEFAULT,DEFAULT);
SELECT * FROM PEDIDO;
CREATE TABLE ARTICULO(
ID INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION MEDIUMTEXT NOT NULL 
);

INSERT INTO ARTICULO VALUES
(DEFAULT, "REFRIGERACION LIQUIDA");
SELECT * FROM ARTICULO;

CREATE TABLE FABRICA(
ID INT PRIMARY KEY AUTO_INCREMENT,
TELEFONO CHAR (9) UNIQUE,
TOTAL_ARTICULO SMALLINT 
);

INSERT INTO FABRICA VALUES
(DEFAULT,"663789541", "20");
SELECT * FROM FABRICA;

CREATE TABLE PEDIDO_CONTIENE_ARTICULO(
CANTIDAD INT, 
ID_PEDIDO INT AUTO_INCREMENT,
ID_ARTICULO INT AUTO_INCREMENT,
PRIMARY KEY (ID_PEDIDO,ID_ARTICULO),
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID),
FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID)
);

INSERT INTO PEDIDO_CONTIENE_ARTICULO VALUES
("50", DEFAULT,DEFAULT);
SELECT * FROM PEDIDO_CONTIENE_ARTICULO;

CREATE TABLE FABRICA_PROVEE_ARTICULO(
STOCK SMALLINT,
ID_FABRICA INT,
ID_ARTICULO INT,
PRIMARY KEY (ID_FABRICA,ID_ARTICULO),
FOREIGN KEY (ID_FABRICA) REFERENCES FABRICA(ID),
FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID),
CONSTRAINT STOCK_POSITIVO CHECK (STOCK>0)
);
CREATE TABLE CLIENTE_USA_DIRECCION(
ID_CLIENTE INT AUTO_INCREMENT,
ID_DIRECCION INT AUTO_INCREMENT,
PRIMARY KEY (ID_CLIENTE,ID_DIRECCIONES),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (ID_DIRECCIONES) REFERENCES DIRECCIONES(ID)
);
INSERT INTO CLIENTE_USA_DIRECCIONES VALUES
(DEFAULT,DEFAULT);
SELECT * FROM CLIENTE_USA_DIRECCIONES;