DROP SCHEMA IF EXISTS CONCESIONARIO;
CREATE SCHEMA CONCESIONARIO;
USE CONCESIONARIO;
CREATE TABLE MARCA(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (50)
);
CREATE TABLE MODELO(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (50), 
ID_MARCA INT,
FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID)
);
CREATE TABLE VERSION(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (50),
POTENCIA VARCHAR (50), 
PRECIO DECIMAL (9,2),
COMBUSTIBLE VARCHAR (30), 
ID_MODELO INT,
FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID)
);
CREATE TABLE EXTRA(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (50), 
DESCUENTO INT
);
CREATE TABLE CLIENTE(
NIF CHAR (9) PRIMARY KEY,
NOMBRE VARCHAR (50),
DIRECCION VARCHAR (50),
TELEFONO INT
);
CREATE TABLE VENDEDOR(
NIF CHAR (9),
NOMBRE VARCHAR (50),DIRECCION,TELEFONO);
NOMBRE VARCHAR (50),DIRECCION,TELEFONO);
VERSION_EQUIPA_EXTRA (ID_VERSION,ID_EXTRA,PRECIO)
CLIENTE_COMPRA_MODELO (NIF_CLIENTE,ID_MODELO,FECHA_COMPRA,MATRICULA,NIF_VENDEDOR)
