DROP SCHEMA IF EXISTS TIENDA;
CREATE SCHEMA TIENDA;
USE TIENDA;
CREATE TABLE EMPLEADO(
NIF CHAR (9) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (30),
APELLIDOS VARCHAR (30)NOT NULL,
ID_SECCION INT,
FOREIGN KEY (ID_SECCION) REFERENCES SECCION(ID)
);
INSERT INTO EMPLEADO VALUES
("123456781","Ramon", "de los altos","123456951"),
("456789122","Javier", "Martinez","789456123");
SELECT * FROM EMPLEADO;
CREATE TABLE SECCION(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBBRE VARCHAR (30)
);
INSERT INTO SECCION VALUES
(DEAFULT, "RAMON");
SELECT * FROM SECCION;
CREATE TABLE CLIENTE(
NIF CHAR (9) PRIMARY KEY,
NOMBRE VARCHAR (30),
APELLIDO VARCHAR (50),
DOMICILIO VARCHAR (50),
CIUDAD VARCHAR (30),
TELEFONO INT UNIQUE
);
INSERT INTO CLIENTE VALUES
("789456123", "JOSE","RAMIREZ","CALLEJON DIAGON","MADRID","663789541");
SELECT * FROM CLIENTE;
CREATE TABLE ARTICULO(
CODIGO VARCHAR (30) PRIMARY KEY
);
INSERT INTO ARTICULO VALUES
("159753456852");
SELECT * FROM ARTICULO;
CREATE TABLE CLIENTE_COMPRA_ARTICULO(
NIF_CLIENTE CHAR (9),
CODIGO_ARTICULO VARCHAR (50),
FECHA_HORA_COMPRA DATETIME,
CANTIDAD INT, 
NIF_EMPLEADO CHAR (9),
PRIMARY KEY (NIF_CLIENTE,CODIGO_ARTICULO, FECHA_HORA_COMPRA, NIF_EMPLEADO),
FOREIGN KEY (NIF_CLIENTE) REFERENCES CLIENTE(NIF),
FOREIGN KEY (CODIGO_ARTICULO) REFERENCES ARTICULO(CODIGO),
FOREIGN KEY (NIF_EMPLEADO) REFERENCES EMPLEADO(NIF)
);
INSERT INTO CLIENTE_COMPRA_ARTICULO VALUES
("789456123", "159753456852","2023-08-12","20","123456789");
SELECT * FROM CLIENTE_COMPRA_ARTICULO;
CREATE TABLE EQUIPO(
CODIGO VARCHAR (30) PRIMARY KEY,
STOCK INT, 
NOMBRE VARCHAR (30),
DESCRIPCION VARCHAR (50),
PRECIO DECIMAL (9,2),
FOREIGN KEY (CODIGO) REFERENCES ARTICULO(CODIGO)
);
INSERT INTO EQUIPO VALUES
("159789963", "50","SSD","MEMORIA","40");
SELECT * FROM EQUIPO ;
CREATE TABLE COMPONENTE(
CODIGO VARCHAR (30) PRIMARY KEY, 
STOCK INT, 
NOMBRE VARCHAR (30),
DESCRIPCION VARCHAR (50),
PRECIO DECIMAL (9,2) DEFAULT (0.0),
FOREIGN KEY (CODIGO) REFERENCES ARTICULO(CODIGO)
);
INSERT INTO COMPONENTE VALUES
("753963147", "20","REFRIGERACION LIQUIDA","BAJAR LA TEMP AL ORDENADOR","129.99");
SELECT * FROM COMPONENTE;
CREATE TABLE EQUIPO_COMPUESTO_COMPONENTE(
CODIGO_EQUIPO VARCHAR (50),
CODIGO_COMPONENTE VARCHAR (50),
CANTIDAD INT,
PRIMARY KEY (CODIGO_EQUIPO, CODIGO_COMPONENTE)
);
INSERT INTO EQUIPO_COMPUESTO_COMPONENTE VALUES
("159789963", "753963147","50");
SELECT * FROM EQUIPO_COMPUESTO_COMPONENTE;