CREATE SCHEMA RESTAURANTE;
USE RESTAURANTE;

CREATE TABLE CATEGORIA (
	NOMBRE VARCHAR(30) PRIMARY KEY,
    DESCRIPCION TINYTEXT 
);
# PLATO (NOMBRE, DESCRIPCION, FOTO ,PRECIO NOMBRE_CATEGORIA)
CREATE TABLE PLATO (
	NOMBRE VARCHAR (30) PRIMARY KEY,
    DESCRIPCION TINYTEXT,
    FOTO BLOB(500),
    PRECIO DECIMAL (5,2),
    NOMBRE_CATEGORIA VARCHAR(30),
    
    FOREIGN KEY (NOMBRE_CATEGORIA) REFERENCES CATEGORIA(NOMBRE)
);

#RECETA (CODIGO, TIEMPO_ELABORACION, DIFICULTAD, NOMBRE_PLATO)
CREATE TABLE RECETA(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT, 
    TIEMPO_ELABORADO TIME,
    DIFICULTAD BLOB(500),
    NOMBRE_PLATO VARCHAR(30),
    FOREIGN KEY (NOMBRE_PLATO) REFERENCES PLATO(NOMBRE)
);
CREATE TABLE INGREDIENTE(
	NOMBRE VARCHAR (30) PRIMARY KEY,
    FOTO BLOB,
    STOCK VARCHAR(30),
    NOMBRE_PLATO VARCHAR(30),
    
    FOREIGN KEY (NOMBRE_PLATO) REFERENCES PLATO(NOMBRE)
    );
    CREATE TABLE RECETA_USA_INGREDIENTE(
	CODIGO INT,
    NOMBRE VARCHAR (30),
    STOCK DECIMAL(5,2),
    UNIDAD_DE_MEDIDA VARCHAR(15),
    
    PRIMARY KEY(CODIGO, NOMBRE),
    
    FOREIGN KEY (CODIGO) REFERENCES RECETA(CODIGO),
    FOREIGN KEY (CODIGO) REFERENCES INGREDIENTE(NOMBRE)
    );
    