USE SAKILA;
SELECT*FROM FILM_ACTOR;
SELECT*FROM PAYMENT;
SELECT*FROM RENTAL;
# EJ1.- ¿CUÁLES SON LAS TARIFAS DE ALQUILER (RENTAL RATE)?
SELECT RENTAL_RATE FROM FILM;
# EJ2.- ¿CUÁNTAS PELÍCULAS DURAN MÁS DE 100 MINUTOS Y TIENEN UN RATING DE PG, R O G?
SELECT COUNT(*) FROM FILM WHERE LENGTH > 100 AND RATING = "PG" AND RATING = "R" OR "G";
# EJ3.- ¿CUÁL ES LA PELÍCULA O PELÍCULAS CON MAYOR DURACIÓN DE LAS QUE CONTIENEN TRAILERS COMO EXTRAS?
SELECT COUNT(*) FROM FILM WHERE SPECIAL_FEATURES LIKE "%TRAILERS%";
# EJ4.- ¿QUÉ PELÍCULAS ESTÁN PROTAGONIZADAS POR UN ASTRONAUTA Y UN ADMINSTRADOR DE BASES DE DATOS (DESCRIPTION)?
SELECT COUNT(*) FROM FILM WHERE DESCRIPTION LIKE "%DATABASE ADMINISTRATOR%" AND TITLE LIKE "%ASTRONAUT";
SELECT*FROM FILM;
# EJ5.- ¿CUÁNTO DURAN, DE MEDIA, LAS PELÍCULAS PROTAGONIZADAS POR EL ACTOR 1 (FILM_ACTOR)?
SELECT AVG(FILM_ID) AS HORAS_MEDIA FROM FILM_ACTOR WHERE ACTOR_ID="1";
# EJ6.- ¿CUÁNTO TARDARÍAMOS (EN HORAS) EN VER TODAS LAS PELÍCULAS DE CATEGORÍA 6 (FILM_CATEGORY)?
SELECT SUM(FILM_ID) AS DURACION_HORAS FROM FILM_CATEGORY WHERE CATEGORY_ID = "6" ;
SELECT*FROM FILM_CATEGORY;