# OSCAR MANUEL BENITO MARTIN
USE WORLD;
#EJ 1 # EJ1 - MUESTRA EL NOMBRE DE LOS PAÍSES Y 
#CREA UN CÓDIGO DE PAÍS CONCATENANDO LAS DOS (2) PRIMERAS LETRAS DEL CONTINENTE, 
#EL CODE2 REPETIDO TRES (3) VECES Y LAS TRES (3) PRIMERAS LETRAS DEL PAÍS (TODO EN MAYÚSCULA).
SELECT NAME, UPPER(CONCAT(LEFT(CONTINENT, 2), REPEAT(CODE2,3), LEFT (NAME,3))) AS CODIGO_NUEVO FROM COUNTRY;
SELECT * FROM COUNTRY;

# EJ2 - MUESTRA UNA LISTA DE LAS REGIONES EN MAYÚSUCLA, 
#Y LA SUPERFICIE TOTAL DE CADA REGIÓN SIN DECIMALES (REDONDEA HACIA ARRIBA).
SELECT UPPER(REGION) AS REGION , SUM(CEIL(SURFACEAREA)) AS SUPERFICIE_TOTAL FROM COUNTRY GROUP BY REGION;
# EJ3 - MUESTRA EL CÓDIGO DE LOS PAÍSES DE EUROPA O ASIA CON MÁS DE 10M DE HABITANTES 
#Y EL NOMBRE DEL PAÍS CONCATENADO CON SU NOMBRE LOCAL (LocalName).
SELECT CODE, CONCAT(NAME, "-", LOCALNAME) AS NOMBRE_LOCAL 
FROM COUNTRY WHERE  POPULATION > 10000000 AND CONTINENT IN("EUROPE","ASIA");
# EJ4 - MUESTRA UNA LISTA DE LOS NOMBRES DE LOS PAISES, SU NOMBRE LOCAL 
#Y UNA COLUMNA BOOLEANA QUE INDICA SI COINICDEN LOS NOMBRES ANTERIORES.
SELECT NAME, LOCALNAME, NAME=LOCALNAME AS COINCIDE FROM COUNTRY;
# EJ5 - MUESTRA UNA LISTA DE LOS PAÍSES QUE HABLAN MÁS DE DOS (2) IDIOMAS DE FORMA OFICIAL
# Y SU ESPERANZA DE VIDA REDONDEADA HACIA ABAJO.
SELECT
	FLOOR(LIFEEXPECTANCY) AS ESPERANZA_DE_VIDA, NAME FROM COUNTRY 
WHERE CODE IN
(SELECT COUNTRYCODE FROM COUNTRYLANGUAGE WHERE ISOFFICIAL = "T"  GROUP BY COUNTRYCODE HAVING COUNT(LANGUAGE)>2);