DROP SCHEMA IF EXISTS PELICULAS;
CREATE SCHEMA PELICULAS;
USE PELICULAS;
CREATE TABLE PELICULA(
ID INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR (100),
ANIO SMALLINT,
NACIONALIDAD VARCHAR (50),
IDIOMA VARCHAR (50),
COLOR BOOLEAN, 
RESTRICCION_EDAD INT,
RESUMEN TEXT (3000),
OBSERVACIONES TEXT
);
CREATE TABLE ACTOR(
NOMBRE VARCHAR (30),
NACIONALIDAD VARCHAR (50),
ID INT PRIMARY KEY AUTO_INCREMENT
);
CREATE TABLE DIRECTOR(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (30),
FECHA_NACIMIENTO DATE,
PAIS_ORIGEN VARCHAR (50)
);
CREATE TABLE ACTOR_ACTUA_PELICULA(
ID_PELICULA INT,
ID_ACTOR INT,
PERSONAJE VARCHAR (30),
PRIMARY KEY (ID_PELICULA, ID_ACTOR, PERSONAJE),
FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID),
FOREIGN KEY (ID_ACTOR) REFERENCES ACTOR(ID)
);
CREATE TABLE DIRECTOR_DIRIGE_PELICULA(
ID_DIRECTOR INT,
ID_PELICULA INT,
PRIMARY KEY (ID_DIRECTOR, ID_PELICULA),
FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR(ID),
FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID)
);
#CREA 2 PELICULAS
#ID,TITULO, AÑO, NACIONALIDAD, IDIOMA, COLOR, RESTRICCION_EDAD, RESUMEN, OBSERVACIONES
INSERT INTO PELICULA VALUES
(DEFAULT,"SEÑOR DE LOS ANILLOS","2000","ESTADOUNIDENSE","INGLES",TRUE,"+18","SE JUNTA LA COMUNIDAD","VIOLENTA"),
(DEFAULT,"SEÑOR DE LOS ANILLOS LAS DOS TORRES","2003","ESTADOUNIDENSE","INGLES",TRUE,"+18","LUCHAN CONTRA SARUMAN","VIOLENTA");
SELECT * FROM PELICULA;
#CADA PELICULA TIENE DOS ACTORES
#NOMBRE, NACIONALIDAD, ID
INSERT INTO ACTOR  VALUES
(DEFAULT,"ELIJAH WOOD","ESTADOUNIDENSE"),
(DEFAULT,"VIGGO MORTENSEN","ESTADOUNIDENSE");
SELECT * FROM ACTOR; 

INSERT INTO ACTOR_ACTUA_PELICULA VALUES
(1, 1, "SEÑOR DE LOS ANILLOS"),
(2, 2, "SEÑOR DE LOS ANILLOS");
SELECT * FROM ACTOR_ACTUA_PELICULA;

# UNO DE LOS ACTORES REALIZA 3 PERSONAJES EN UNA MISMA PELICULA
# CREA DOS DIRECTORES
#ID,NOMBRE,FECHA_NACIMIENTO,PAIS_ORIGEN
INSERT INTO DIRECTOR VALUES
(DEFAULT, "PETER JACKSON","1961-10-31","ESTADOUNIDENSE"),
(DEFAULT, " Fran Walsh","1969-01-10","ESTADOUNIDENSE");
SELECT * FROM DIRECTOR
#UNA DE LAS PELICUALS ESTA COODIRIGIDA