#==========CREAR USUARIO==========#
CREATE USER "OSCAR" IDENTIFIED BY "1234"; # ENTRA A CUALQUIERA
CREATE USER 'RON'@'172.16.0.7' IDENTIFIED BY '1234'; # ENTRA SOLO A LA IP PUESTA

SELECT USER, HOST FROM MYSQL.USER;

#===============PERMISOS============#
SHOW GRANTS FOR OSCAR; #MUESTRA LOS PERMISOS QUE TIENE EL USUARIO.
GRANT ALL PRIVILEGES ON *.* TO ALEJANDRO; # ESTO DA TODOS LOS PERMISOS
REVOKE ALL PRIVILEGES ON *.* FROM ALEJANDRO; # QUITA TODOS LOS PERMISOS
FLUSH PRIVILEGES; #ACTUALIZA LOS PRIVILEGIOS

CREATE FUNCTION MAX_POPULATION()
RETURNS INT
BEGIN
# LO QUE VA DENTRO EN LA FUNCIÓN
END$
DELIMITER ;
# EJ1 - CREA UN USUARIO system CON CONTRASEÑA 'efd5r26' QUE QUE PUEDA CONECTARSE DESDE CUALQUIER MAQUINA AL SERVIDOR MYSQL 
#       Y QUE TENGA TODOS LOS PRIVILEGIOS SOBRE TODOS LOS OBJETOS DE MYSQL (IGUAL QUE ROOT). TENED EN CUENTA QUE ESTE
#       USUARIO VA A TENER QUE CONCEDER DISTINTOS PRIVILEGIOS A OTROS USUARIOS. 
#     - CREA UNA CONEXION CON EL USUARIO system. HAZ EL RESTO DE APARTADOS USANDO ESTE USUARIO. 
CREATE USER 'SYSTEM' IDENTIFIED BY '12345'; 
GRANT ALL PRIVILEGES ON *.* TO 'SYSTEM' WITH GRANT OPTION; #-> ESTO ES PARA DAR A LOS OTROS USUSARIOS PRIVILEGIOS
SHOW GRANTS FOR 'SYSTEM';
FLUSH PRIVILEGES;

