USE EMPLOYEES;
SELECT EMP.FIRST_NAME AS NOMBRE, MONTH(S.TO_DATE) AS MES , AVG(S.SALARY) AS SALARIO_MEDIO 
FROM SALARIES S 
JOIN EMPLOYEES EMP ON EMP.EMP_NO = S.EMP_NO
WHERE S.TO_DATE >= DATE_SUB('2000-01-1', INTERVAL 1 YEAR)
GROUP BY NOMBRE, MES
ORDER BY NOMBRE, MES;

SELECT DEP.DEPT_NAME AS NOMBRE_DEPARTAMENTO, MONTH(S.TO_DATE) AS MES,
ROUND(AVG(S.SALARY)) AS SALARIO_MEDIO 
FROM DEPARTMENTS DEP
JOIN DEPT_MANAGER DM ON DM.DEPT_NO = DEP.DEPT_NO
JOIN EMPLOYEES EMP ON EMP.EMP_NO=DM.EMP_NO
JOIN SALARIES S ON EMP.EMP_NO=S.EMP_NO
WHERE S.TO_DATE >= DATE_SUB('2000-01-1', INTERVAL 1 YEAR)
GROUP BY NOMBRE_DEPARTAMENTO, MES
ORDER BY NOMBRE_DEPARTAMENTO, MES;

SELECT DEP.DEPT_NAME AS NOMBRE_DEPARTAMENTO, MONTH(S.TO_DATE) AS MES,
       ROUND(AVG(S.SALARY)) AS SALARIO_MEDIO
FROM EMPLOYEES E
JOIN SALARIES S ON E.EMP_NO = S.EMP_NO
JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
JOIN DEPARTMENTS DEP ON DE.DEPT_NO = DEP.DEPT_NO
WHERE S.TO_DATE >= DATE_SUB('2000-01-1', INTERVAL 1 YEAR)
GROUP BY NOMBRE_DEPARTAMENTO, MES
ORDER BY NOMBRE_DEPARTAMENTO, MES;

SELECT ROUND(SUM(S.SALARY)*1.3) AS GASTO_TOTAL
FROM SALARIES S
WHERE S.TO_DATE >= DATE_SUB('2000-01-1', INTERVAL 1 YEAR);

SELECT ROUND((SALARIO_HOMBRE - SALARIO_MUJER) / SALARIO_HOMBRE * 100, 2) AS BRECHA_SALARIAL_PORCENTAJE
FROM (SELECT
        AVG(CASE WHEN GENDER = 'M' THEN SALARY END) AS SALARIO_HOMBRE,
        AVG(CASE WHEN GENDER = 'F' THEN SALARY END) AS SALARIO_MUJER
    FROM SALARIES
    JOIN EMPLOYEES ON SALARIES.EMP_NO = EMPLOYEES.EMP_NO
) AS CONSULTA_SALARIO;
SELECT COUNT(*) AS CANTIDAD_TOTAL_EMPLEADOS
FROM EMPLOYEES;
SELECT D.DEPT_NAME AS DEPARTAMENTO, COUNT(*) AS CANTIDAD_EMPLEADOS
FROM EMPLOYEES E
JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
JOIN DEPARTMENTS D ON DE.DEPT_NO = D.DEPT_NO
GROUP BY DEPARTAMENTO;
SELECT T.TITLE AS PUESTO_DE_TRABAJO, COUNT(*) AS CANTIDAD_TRABAJADORES
FROM EMPLOYEES E
JOIN TITLES T ON E.EMP_NO = T.EMP_NO
GROUP BY PUESTO_DE_TRABAJO;