USE SEGUROS;
SELECT * FROM CLIENTE; 
SELECT * FROM CLIENTE_ASEGURA_VEHICULO; #(DNI_CLIENTE=CLIENTE.DNI) #(NUMERO_BASTIDOR_VEHICULO=VEHICULO.NUMERO_BASTIDOR)
SELECT * FROM COBERTURA; 
SELECT * FROM POLIZA; #(ID_VEHICULO_ASEGURADO=CLIENTE_ASEGURA_VEHICULO.ID)
SELECT * FROM POLIZA_ASOCIA_COBERTURA; #(CODIGO_COBERTURA=COBERTURA.CODIGO) #(NUMERO_POLIZA=POLIZA.NUMERO_POLIZA)
SELECT * FROM SINIESTRO; #(NUMERO_POLIZA = POLIZA.NUMERO_POLIZA)
SELECT * FROM VEHICULO;
# EJ1 ¿MUESTRA UNA LISTA CON LAS MARCAS DE LOS VEHÍCULOS Y LA CANTIDAD DE SINIESTROS QUE HA SUFRIDO CADA MARCA?
SELECT VE.MARCA, COUNT(SI.ID) AS CANTIDAD_SINIESTRO FROM VEHICULO AS VE 
JOIN CLIENTE_ASEGURA_VEHICULO AS CV 
ON VE.NUMERO_BASTIDOR=CV.NUMERO_BASTIDOR_VEHICULO
JOIN SINIESTRO AS SI ON VE.NUMERO_BASTIDOR=SI.NUMERO_POLIZA
GROUP BY VE.MARCA; 
# EJ2 MUESTRA EL NOMBRE DE LOS 5 CLIENTES QUE MÁS PAGAN POR LAS COBERTURAS.
SELECT CL.NOMBRE, SUM(CO.CUANTIA) AS CANTIDAD FROM CLIENTE AS CL 
JOIN CLIENTE_ASEGURA_VEHICULO AS CV ON CL.DNI=CV.DNI_CLIENTE
JOIN POLIZA AS PO ON CV=PO.ID_VEHICULO_ASEGURADO
JOIN POLIZA_ASOCIA_VEHICULO AS PV ON PO.NUMERO_POLIZA=PV.NUMERO_POLIZA
JOIN COBERTURA AS CO ON PV.CODIGO_COBERTURA=CB.CODIGO
GROUP BY CANTIDAD LIMIT 5;
# EJ3 MUESTRA EL NOMBRE DEL CLIENTE CUYOS SINIESTROS ACUMULAN LA MAYOR CUANTÍA.
SELECT CL.NOMBRE, SI.CUANTIA FROM CLIENTE AS CL 
JOIN CLIENTE_ASEGURA_VEHICULO AS CV ON CL.DNI=DNI_CLIENTE
JOIN POLIZA AS PO ON CV.DNI_CLIENTE=PO.ID_VEHICULO_ASEGURADO
JOIN SINIESTRO AS SI ON PO.NUMERO_POLIZA=SI.NUMERO_POLIZA
ORDER BY SI.CUANTIA DESC LIMIT 1;

# EJ4 MUESTRA LOS COLORES DE LOS VEHÍCULOS Y CUÁNTO PAGAN DE MEDIA POR SUS COBERTURAS.
SELECT VE.COLOR, AVG(CO.CUANTIA) AS PAGAR FROM VEHICULO AS VE
JOIN CLIENTE_ASEGURA_VEHICULO AS CAV ON VE.NUMERO_BASTIDOR=CAV.NUMERO_BASTIDOR_VEHICULO
JOIN POLIZA AS POL ON CAV.ID=POL.ID_VEHICULO_ASEGURADO
JOIN POLIZA_ASOCIA_COBERTURA AS PAC ON POL.CODIGO_COBERTURA=PAC.NUMERO_POLIZA
JOIN COBERTURA AS CO ON CO.CODIGO=PAC.CODIGO_CUANTIA
ORDER BY PAGAR;