#OSCAR MANUEL BENITO MARTIN 
USE WORLD;

# EJ1 - MUESTRA EL NOMBRE DE LOS PAÍSES Y SU GNPold.
#     - SI EL GNPold ES NULO, MUESTRA EL GNP.
#     - ADEMÁS, MUESTRA UNA COLUMNA QUE CLASIFIQUE LOS PAÍSES DEL SIGUIENTE MODO:
#          - GNP MENOR QUE 20.000: PAÍS POBRE.
#          - GNP ENTRE 20.000 Y 200.000: PAÍS PROMEDIO.
#          - GNP MAYOR QUE 200.000: PAÍS RICO.
SELECT * FROM COUNTRY;
SELECT NAME, IFNULL(NULL,GNPOLD), GPN,
CASE
		WHEN GPN < 20000 THEN "PAÍS POBRE"
		WHEN GPN BETWEEN 20000 AND 2000000 THEN "PAÍS PROMEDIO"
		WHEN GENP > 200000 THEN "PAÍS RICO"
		ELSE "NO HAY PAIS"
        END AS CLASIFICACION_PAISES
 FROM COUNTRY;
# EJ2 - CREA UN ÍNDICE PARA LAS COLUMNAS LANGUAGE E ISOFFICIAL DE LA TABLA 
#       COUNTRYLANGUAGE (SOLO UN ÍNDICE).

USE SAKILA;

# EJ3 - ¿CUÁNTOS AÑOS LLEVA CERRADO EL VIDEOCLUB? (SE CERRÓ EL DÍA DEL ÚLTIMO ALQUILER)

# EJ4 - ¿LA QUINCENA INFLUYE EN LOS INGRESOS POR ALQUILER? MUESTRA EL PAGO PROMEDIO DE 
#       ALQUILER AGRUPANDO POR PRIMERA Y SEGUNDA QUINCENA.

# EJ5 - LAS PELÍCULAS NC-17 NO PUEDEN SER ALQUILADAS POR NADIE MENOR DE 17 AÑOS.
#       MUESTRA UNA LISTA CON EL NOMBRE DE LA PELÍCULA ALQUILADA (SOLO PELÍCULAS NC-17), 
#       LA FECHA DEL ALQUILER Y LA FECHA DE NACIMIENTO MÍNIMA QUE DEBERÍA TENER EL CLIENTE 
#       EN ESE MOMENTO.