SELECT * FROM CITY;
#==================BORRADO DE DATOS==================#
TRUNCATE TABLE CITY; # TRUNCATE -> ELIMINA EL CONTENIDO SIN BORRAR LA TABLA, BORRA LOS DATOS DE FORMA PERMANENTE
DELETE FROM CITY;
# BORRA LA ESTRUCTURA DE LA TABLA (INCLUIDO EL CONTENIDO)
DROP TABLE COUNTRYLANGUAGE;
#ELIMINA FILAS  DETERMINADAS ES LO MISMO QUE EL TRUNCATE 
DELETE FROM COUNTRYLANGUAGE WHERE COUNTRYCODE="ESP" ;

#==================TRANSACCIONES==================#
SELECT * FROM COUNTRYLANGUAGE WHERE COUNTRYCODE="ESP";
DELETE FROM COUNTRYLANGUAGE WHERE COUNTRYCODE="ESP" ;
ROLLBACK; # EL ROLLBACK ES VOLVER ATRAS DE TODOS LOS PROCESOS QUE HAYAS BORRADO
COMMIT; # LOS CAMBIOS SON PERMANENTES

#SET SQL_SAFE_UPDATES=FALSE; #DESACTIVA EL MODO SEGURO (SOLO PUEDO MODIFICAR USANDO PKs EN EL WHERE)

#==================ACTUALIZACION DE DATOS==================#
SELECT * FROM COUNTRY WHERE CODE="ESP";
UPDATE COUNTRY SET POPULATION=POPULATION*1.1 WHERE COUNTRYCODE="ESP";
#==================EJERCICIOS==================#

# EJ1 - ELIMINA FRANCIA DEL PLANETA 
DELETE FROM COUNTRY WHERE NAME="FRANCE";
# EJ2 - AUMENTA UN 10% LA POBLACION DE LOS  PAISES AFRICANOS
SELECT * FROM COUNTRY WHERE CONTINENT="AFRICA";
UPDATE COUNTRY SET POPULATION=POPULATION*1.1 WHERE  CONTINENT="AFRICA";
# EJ3  FUSIONA ESPAÑA CON PORTUGAL Y LOS PAISES AMERICANOS
# 		FUSIONA LA SUPERFICIE, POBLACION, GNP Y ESPERANZA DE VIDA MEDIA
#		EL NUEVO PAIS DEBE SER LLAMADO "IMPERIO ESPAÑOL"
SELECT * FROM COUNTRY; 
UPDATE COUNTRY SET 
SURFACEAREA=(SELECT SUM(SURFACEAREA) FROM COUNTRY WHERE NAME="PORTUGAL" OR NAME="SPAIN" OR CONTINENT LIKE "%AMERICA%"),
POPULATION=(SELECT SUM(POPULATION) FROM COUNTRY WHERE NAME="PORTUGAL" OR NAME="SPAIN" OR CONTINENT LIKE "%AMERICA%"),
GNP=(SELECT SUM(GNP) FROM COUNTRY WHERE NAME="PORTUGAL" OR NAME="SPAIN" OR CONTINENT LIKE "%AMERICA%" ),
LIFEEXPECTANCY=(SELECT AVG(LIFEEXPECTANCY) FROM COUNTRY WHERE NAME="PORTUGAL"  OR NAME="SPAIN" OR CONTINENT LIKE "%AMERICA%")
WHERE CODE="ESP";

# EJ4 - CAMBIA LA CIUDAD DE GRIBALTAR PARA QUE PASE A SER ESPAÑOLA
UPDATE CITY SET COUNTRYCODE="ESP" WHERE NAME="GRIBRALTAR"; 
# EJ5 - TODAS LAS CIUDADES DE MURCIA SON INCORPORADAS POR LA COMUNIDAD VALENCIANA
USE WORLD;
SELECT * FROM CITY;
SELECT DISTINCT DISTRICT FROM CITY WHERE COUNTRYCODE="ESP"; 
UPDATE CITY SET DISTRICT="VALENCIA" WHERE DISTRICT="MURCIA";

# EJ6 - CREA UNA COLUMNA NUEVA EN LA TABLA FILM QUE MUESTRE LA DURACION DE LAS PELICULAS EN FORMATO TIME
USE SAKILA;
SELECT * FROM FILM;
SET SQL_SAFE_UPDATES=FALSE; #ESTO HAY QUE EJECUTARLO PARA QUE LO DE ABAJO TE FUNCIONE
#EL ERROR QUE TE APARECE ES Error Code: 1175. You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column.  To disable safe mode, toggle the option in Preferences -> SQL Editor and reconnect.	0.000 sec
ALTER TABLE FILM ADD COLUMN (DURACION TIME);
UPDATE FILM SET DURACION=SEC_TO_TIME(LENGTH*60);
SELECT DURACION FROM FILM;
# EJ7 - CREA UNA COLUMNA EDAD_MINIMA EN FILM QUE MUESTRA LA EDAD MINIMA PARA ALQUILAR LA PELICULA:
# G -> TODOS LOS PUBLICOS 
# PG -> MAYORES DE 7 AÑOS
# PG-13 -> MAS DE 13 AÑOS
# R Y NC-17 -> MAS DE 17 AÑOS 
ALTER TABLE FILM ADD COLUMN (EDAD_MINIMA DATE);
UPDATE FILM SET EDAD_MINIMA=DATE_ADD(NOW(), INTERVAL -7 YEAR) WHERE RATING="PG";
UPDATE FILM SET EDAD_MINIMA=DATE_ADD(NOW(), INTERVAL -13 YEAR) WHERE RATING="PG-13";
UPDATE FILM SET EDAD_MINIMA=DATE_ADD(NOW(), INTERVAL -17 YEAR) WHERE RATING IN ("R", "NC-17");
SELECT * FROM FILM;

# EJ8 - BORRA LAS PELICULAS QUE DUREN MENOS DE DOS HORAS
DELETE FROM FILM WHERE LENGTH < 120;
# EJ9 - BORRA LAS PELICULAS QUE NO DISPONGAN DE NINGUNA COPIA EN EL INVENTARIO
DELETE FROM FILM WHERE FILM_ID IN (SELECT F.FILM_ID FROM FILM F
LEFT JOIN INVENTORY INV ON F.FILM_ID=INV.FILM_ID
WHERE INV.INVENTORY_ID IS NULL);
DELETE FROM FILM;



#====================
USE WORLD;
SELECT 
	CI.NAME,
	CO.NAME FROM CITY CI 
JOIN COUNTRY CO ON CI.COUNTRYCODE= CO.CODE;




